# Generated by Django 6.1.1 on 2026-09-29 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipos', models.PositiveIntegerField()),
                ('dias_iniciales', models.PositiveIntegerField()),
                ('dias_adicionales', models.PositiveIntegerField(default=0)),
                ('modalidad', models.CharField(choices=[('ciudad', 'Dentro de la ciudad'), ('fuera', 'Fuera de la ciudad'), ('establecimiento', 'Dentro del establecimiento')], max_length=20)),
                ('fecha_alquiler', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alquileres', to='facturApp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje_descuento_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descuento_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_modalidad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_modalidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_factura', models.DateTimeField(auto_now_add=True)),
                ('alquiler', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='facturApp.alquiler')),
            ],
        ),
    ]
